from __future__ import annotations

import getpass
import grp
import os
import pwd
import subprocess
import tempfile
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SYSTEMD_UNIT_PATH = Path("/etc/systemd/system/mylibrary.service")
GENERATED_MARKER = "# Generated by MyLibrary; edit by reinstalling with ./mylibrary service install"


def service_account(requested_user: str | None = None) -> tuple[str, str]:
    user = requested_user or os.environ.get("SUDO_USER") or getpass.getuser()
    if user == "root" and requested_user is None:
        raise ValueError("Refusing to run MyLibrary as root. Pass --user with a non-root account.")
    try:
        account = pwd.getpwnam(user)
    except KeyError as error:
        raise ValueError(f"System user does not exist: {user}") from error
    return user, grp.getgrgid(account.pw_gid).gr_name


def render_unit(user: str, group: str, host: str = "127.0.0.1", port: int = 8765) -> str:
    if not 1 <= port <= 65535:
        raise ValueError("Port must be between 1 and 65535")
    if any(character.isspace() for character in host) or not host:
        raise ValueError("Host must be a single address without whitespace")
    root = PROJECT_ROOT.resolve()
    launcher = root / "mylibrary"
    data_dir = root / "data"
    root_value = _unit_path(root)
    launcher_value = _unit_quote(launcher)
    data_value = _unit_path(data_dir)
    return f"""{GENERATED_MARKER}
[Unit]
Description=MyLibrary web interface and optional Telegram paper bot
Documentation={root.joinpath('README.md').as_uri()}
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User={user}
Group={group}
WorkingDirectory={root_value}
ExecStart={launcher_value} run --host {host} --port {port}
Restart=always
RestartSec=5s
TimeoutStopSec=20s
KillSignal=SIGINT
Environment=PYTHONUNBUFFERED=1
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ReadWritePaths={data_value}

[Install]
WantedBy=multi-user.target
"""


def install_service(unit: str, user: str) -> None:
    require_root()
    data_dir = PROJECT_ROOT / "data"
    if not data_dir.exists():
        account = pwd.getpwnam(user)
        data_dir.mkdir(parents=True)
        os.chown(data_dir, account.pw_uid, account.pw_gid)
    SYSTEMD_UNIT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=SYSTEMD_UNIT_PATH.parent, delete=False) as temporary:
        temporary.write(unit)
        temporary_path = Path(temporary.name)
    temporary_path.chmod(0o644)
    temporary_path.replace(SYSTEMD_UNIT_PATH)
    subprocess.run(["systemctl", "daemon-reload"], check=True)
    subprocess.run(["systemctl", "enable", SYSTEMD_UNIT_PATH.name], check=True)
    subprocess.run(["systemctl", "restart", SYSTEMD_UNIT_PATH.name], check=True)


def uninstall_service() -> None:
    require_root()
    if not SYSTEMD_UNIT_PATH.exists():
        return
    if GENERATED_MARKER not in SYSTEMD_UNIT_PATH.read_text(encoding="utf-8"):
        raise ValueError(f"Refusing to remove an unmanaged unit: {SYSTEMD_UNIT_PATH}")
    subprocess.run(["systemctl", "disable", "--now", SYSTEMD_UNIT_PATH.name], check=False)
    SYSTEMD_UNIT_PATH.unlink()
    subprocess.run(["systemctl", "daemon-reload"], check=True)


def require_root() -> None:
    if os.geteuid() != 0:
        raise PermissionError("System service changes require root. Run this command with sudo.")


def _unit_quote(value: Path) -> str:
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _unit_path(value: Path) -> str:
    return "".join(f"\\x{ord(character):02x}" if character.isspace() else character for character in str(value))
